param(
    [Parameter(Mandatory=$true, HelpMessage="The full path to the .cer file")][String] $CertPath,
    [Parameter(Mandatory=$true, HelpMessage="Provide the client ID generated by app-catalog/AppReqNew.aspx when registering the app")][String] $SPAppClientID,
    [Parameter(Mandatory=$true, HelpMessage="The url of the site collection the app will be installed at. ex: https://sharepointdev.gc.wsu.edu/sites/Test")][String] $WebUrl
) 
ECHO ON

# Stop if there's an error
$ErrorActionPreference = "Stop"


# Get the certificate
$certificate = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($CertPath)

# Make the certificate a trusted root authority in SharePoint
New-SPTrustedRootAuthority -Name $CertPath -Certificate $certificate 

# Get the GUID of the authentication realm of the
$Web = Get-SPWeb $WebURL
$sc = Get-SPServiceContext –Site $Web.Site
$realm = Get-SPAuthenticationRealm –ServiceContext $sc

# Must use the client ID as the specific issuer ID. Must be lower-case!
$specificIssuerId = New-Object System.String($SPAppClientID).ToLower()

# Create full issuer ID in the required format
$fullIssuerIdentifier = $specificIssuerId + '@' + $realm 

# Register the token issuer
New-SPTrustedSecurityTokenIssuer -Name $specificIssuerId -Certificate $certificate -RegisteredIssuerName $fullIssuerIdentifier
Register-SPAppPrincipal -NameIdentifier $fullIssuerIdentifier -Site $Web -DisplayName $specificIssuerId